# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ssn}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jason Harrelson"]
  s.date = %q{2010-11-05}
  s.description = %q{Encapsulates functionality for storing an unformatted SSN but formatting the SSN on print.}
  s.email = %q{jason@lookforwardenterprises.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/ssn.rb",
     "lib/ssn/active_record_extensions.rb",
     "lib/ssn/social_security_number.rb",
     "script/console",
     "script/environment.rb",
     "script/seed.rb",
     "spec/database.yml",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/ssn_spec.rb",
     "ssn.gemspec"
  ]
  s.homepage = %q{http://github.com/midas/ssn}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Encapsulates functionality for storing an unformatted SSN but formatting the SSN on print.}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/ssn_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

